### ISSUE TITLE
example file link does not match example txt file

### ISSUE THREAD

**Issue by LisaSikkema** [zzhu33/FASTR#2]
Hi there,

Thanks for developing this pipeline! 
I was going through your test run instructions and noticed that the link to the test fastqs you describe contains other files than your exampleInputNames.txt:
![Screenshot 2021-09-03 at 14 13 06](https://user-images.githubusercontent.com/32548783/132003384-1f56c688-de2a-4261-843b-1b1626a71f70.png)
Seems like it is unpaired data (if I'm correct, I only see I1 and RA files) as opposed to the example data you discuss in the readme, so maybe a completely different dataset?

Also (and unrelated), I had to install psutil to be able to run scSplitter.py, so you could add that to your dependencies!

**Comment by LisaSikkema** [comment]
I think I found the correct link, it was a number switch (1.2.0 instead of 2.1.0):
old:
http://cf.10xgenomics.com/samples/cell-exp/1.2.0/hgmm_100/hgmm_100_fastqs.tar
new:
http://cf.10xgenomics.com/samples/cell-exp/2.1.0/hgmm_100/hgmm_100_fastqs.tar

**Comment by zzhu33** [comment]
Sorry for not responding! Thank you very much for your comments; I have made corrections to the readme.
