### ISSUE TITLE
chemistry version for spatial data

### ISSUE THREAD

**Issue by LisaSikkema** [zzhu33/FASTR#4]
Hi there!

Possibly naive question: I'd like to run scSplitter on Visium spatial transcriptomic data, and was wondering how I should set the 10X version parameter in that case. Is visium chemistry v1 the same as single cell chemistry v1, in terms of fastq/read characteristics? 

Thanks!

**Comment by zzhu33** [comment]
Sorry for taking so long to respond. I wrote this quite a while ago and haven't been monitoring the repository. Unfortunately, this isn't designed for the format of visium reads, although you probably already knew from Tao's email. I have also included his perl script and reorganized the repository. Please let me know if you run into any issues. I'll close this issue in a few days.

Thanks, 
James

**Comment by LisaSikkema** [comment]
Thanks a lot! I have a few questions about the perl script:
1. What is the barcode_file in there? Is it the output barcode file from e.g. space ranger, that looks something like below?
```
$ head -5 sample1_barcodes.tsv 
AAACAAGTATCTCCCA-1
AAACATTTCCCGGATT-1
AAACCTAAGCAGCCGG-1
AAACGAGACGGTTGAT-1
AAACGGGCGTACGGGT-1
```
2. Could you maybe help me point to specific parameters etc. in the perl script that are likely experiment-dependent?

**Comment by LisaSikkema** [comment]
I now tried running 
```
fastq1=/home/lisa/SRR11832354_1.fastq
fastq2=/home/lisa/SRR11832354_2.fastq
barcodes=/home/lisa/GSM4565823_barcodes.tsv
outdir=/home/lisa/tempout
perl split_ST.pl $fastq1 $fastq2 $barcodes $outdir
```
(I also tried with gzipped fastqs)
But am getting this error:
```
gzip: /home/lisa/SRR11832354_1.fastq: not in gzip format

gzip: /home/lisa/SRR11832354_2.fastq: not in gzip format
Unsuccessful stat on filename containing newline at split_ST.pl line 73.
Unsuccessful stat on filename containing newline at split_ST.pl line 73.
Unsuccessful stat on filename containing newline at split_ST.pl line 73.
Unsuccessful stat on filename containing newline at split_ST.pl line 73.
```
With the latter lines repeating many times.
Any idea what the problem could be? (might be related to my post above)

**Comment by zzhu33** [comment]
I believe the script expects compressed fastq files (.gz), the barcode files should be the tsv from cellranger, and there aren't really any parameters for the script. Let me ask Tao to take a look to be sure.

**Comment by LisaSikkema** [comment]
Thanks! I also tried with gzipped files but that didn’t prevent the “unsuccessful stat…” errors. So there must be another problem..

**Comment by wtwt5237** [comment]
@LisaSikkema , what does your barcode file looks like? Could you please share it?

**Comment by LisaSikkema** [comment]
Yes! I'm using this dataset, in case that is of any help:
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE144239
An example of a barcode file is:
[GSM4565823_barcodes_suffix_removed.txt](https://github.com/zzhu33/scSplitter/files/7215812/GSM4565823_barcodes_suffix_removed.txt)
(Changed format to .txt for compatibility with GitHub). In this file I removed the automatically added -1 suffix from every line, I also tried with the suffix, but they all give the same error.

**Comment by LisaSikkema** [comment]
There's also this barcodes file on the GEO page (don't know exactly what it is, a list of barcode frequencies across all samples?), and using that as barcodes file resulted in no output nor printed errors...
[GSE144239_ST_barcode_id.txt](https://github.com/zzhu33/scSplitter/files/7217833/GSE144239_ST_barcode_id.txt)

**Comment by wtwt5237** [comment]
Hi Lisa

The barcodes file looks good to me. It is not very obvious for me to see where things went wrong. Really sorry about the inconvenience. Since it's not very easy to transfer the seq data and actually, this perl script is mostly for our internal use, which we didn't plan to release originally, would you mind doing some debugging on your end to see where things went wrong?

You can do something like: "perl -d split_ST.pl $fastq1 $fastq2 $barcodes $outdir", and type "n" at every line, to at least see which line of code yields this error, and what are the status of the intermediate files at the occurrence of the error?

Thanks!

Tao

**Comment by zzhu33** [comment]
@LisaSikkema Can you show me the first few lines of the $fastq1 file?

**Comment by LisaSikkema** [comment]
I think I solved it! I used the first barcodes file I posted above, removed the -1 suffix from every line, and then split by "\n" instead of "\t" in line 15, and changed the barcode length to 16 in line 32!

**Comment by LisaSikkema** [comment]
I was wondering why you guys do the reverse complement step, is that important for the mutation calling after or something?

**Comment by wtwt5237** [comment]
Lisa, great to know the problem has been solved!!

Yes, it's more regular for the wes/rna-seq data to be in the format of reverse-complemented paired-end seq data. But I think bwa mem and STAR can automatically handle all situations anyway.

**Comment by LisaSikkema** [comment]
Ok good to know! Thanks

**Comment by zzhu33** [comment]
@LisaSikkema I suspected that barcode length was the issue; glad to know that you have solved it.
